version: '3.4'

services:
  rabbitmq-test:
    ports:
      - "15672:15672"
      - "5672:5672"

  redis-test:
    ports:
      - "6379:6379"

  postgresql-test:
    environment:
      - POSTGRES_USER=corpspace
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"

  nosql-test:
    ports:
      - "27017:27017"

  identity-api-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5104
      - XamarinCallback=http://${CSP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5105/xamarincallback
      - ConnectionString=${CSP_AZURE_IDENTITY_DB:-Database=Corpspace.Services.IdentityDb;User Id=corpspace;Password=corpspace;Host=localhost;Port=5432;sslmode=false;}
      - MobileAggClient=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5120
      - WebAggClient=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5121
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5105:80"

  payment-api-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${CSP_AZURE_SERVICE_BUS:-rabbitmq-test}
      - EventBusUserName=${CSP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${CSP_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5108:80"
