version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The CSP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     CSP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
      
  postgresql:
    environment:
      - POSTGRES_USER=corpspace
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - csp-postgres:/var/opt/postgres
    ports:
      - "127.0.0.1:5432:5432"

  nosqldata:
    ports:
      - "27017:27017"
    volumes:
      - csp-nosqldata:/data/db

  redis:
    ports:
      - "6379:6379"
    volumes:
      - csp-redis:/data

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5104
      - XamarinCallback=http://${CSP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5105/xamarincallback
      - ConnectionString=${CSP_AZURE_IDENTITY_DB:-Database=Corpspace.Services.IdentityDb;User Id=corpspace;Password=corpspace;Host=localhost;Port=5432;sslmode=false;}
      - MobileAggClient=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5120
      - WebAggClient=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5121
      - WebhooksApiClient=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5113
      - WebhooksWebClient=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5114
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5105:80"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${CSP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${CSP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${CSP_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - Serilog__MinimumLevel__Override__payment-api.IntegrationEvents.EventHandling=Verbose
      - Serilog__MinimumLevel__Override__Corpspace.BuildingBlocks.EventBusRabbitMQ=Verbose
    ports:
      - "5108:80"

  webhooks-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${CSP_AZURE_WEBHOOKS_DB:-Database=Corpspace.Services.WebhooksDb;User Id=corpspace;Password=corpspace;Host=localhost;Port=5432;sslmode=false;}
      - EventBusConnection=${CSP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${CSP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${CSP_SERVICE_BUS_PASSWORD}
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5105
    ports:
      - "5113:80"

  mobile-api-gw:
    volumes:
      - ./ApiGateways/Envoy/config/csp-mobile:/etc/envoy
    ports:
    - "5200:80"
    - "15200:8001"

  web-api-gw:
    volumes:
      - ./ApiGateways/Envoy/config/csp-web:/etc/envoy
    ports:
    - "5202:80"
    - "15202:8001"

  mobile-agg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__identity=http://identity-api
      - IdentityUrlHC=http://identity-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - IdentityUrlExternal=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5105
    ports:
      - "5120:80"

  web-agg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__identity=http://identity-api
      - IdentityUrlHC=http://identity-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - IdentityUrlExternal=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5105
    ports:
      - "5121:80"

  web-status:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Angular HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://angular-client/hc
      - HealthChecksUI__HealthChecks__1__Name=Web Aggregator GW HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://web-agg/hc
      - HealthChecksUI__HealthChecks__2__Name=Mobile Aggregator HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://mobile-agg/hc
      - HealthChecksUI__HealthChecks__3__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__4__Name=Payments HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://payment-api/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5107:80"

  angular-client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - PurchaseUrl=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5202
      - IdentityUrlHC=http://identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - SignalrHubUrl=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5104:80"

  webhooks-client:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Token=6168DB8D-DC58-4094-AF24-483278923590      # Webhooks are registered with this token (any value is valid) but the client won't check it
      - IdentityUrl=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - CallBackUrl=http://${CSP_EXTERNAL_DNS_NAME_OR_IP}:5114
      - WebhooksUrl=http://webhooks-api
      - SelfUrl=http://webhooks-client/
    ports:
      - "5114:80"
volumes:
  csp-postgres:
    external: false
  csp-nosqldata:
    external: false
  csp-redis:
    external: false

