name: codecov and build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore Corpspace.sln
      - name: Build
        run: dotnet build Corpspace.sln --no-restore
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3